# TODO write a description for this script
# @author
# @category _Custom
# @keybinding
# @menupath
# @toolbar

import ghidra
from ghidra.app.decompiler.flatapi import FlatDecompilerAPI
from ghidra.app.script import GhidraState
from ghidra.app.util.cparser.C import CParser
from ghidra.program.flatapi import FlatProgramAPI
from ghidra.program.model.address import Address
from ghidra.program.model.data import (ArrayDataType, DataTypeConflictHandler,
                                       DataTypeManager, StringDataType,
                                       StructureDataType)
from ghidra.program.model.listing import Program


def get_state():
	# type: () -> GhidraState
	return getState()

def as_struct(x):
	# type: (DataType) -> StructureDataType
	return x

state = get_state()
program = state.getCurrentProgram()

fpapi = FlatProgramAPI(program)

fdapi = FlatDecompilerAPI(fpapi)

dtype = as_struct(fpapi.getDataTypes("Cell")[0])
print(type(dtype))
print(dtype.getComponentAt(0))
fn = fpapi.getFunctionContaining(state.currentAddress)
src = str(fdapi.decompile(fn))
print(src)
ty_map = {
	"Bool": "bool",
	# "String": "StdString",
	# typically mapped to struct inside a Cell so skip this
	"Int": "int",
	"Float": "float",
	"Double": "double",
}
gets = src.split("GetGlobal")
for get in gets:
	ty = get.split("(")[0]
	if ty not in ty_map.keys():
		continue
	field_name = get.split("(")[1].split(")")[0]
	if "field" not in field_name:
		continue
	ty_normal = ty_map[ty]
	correct_name = get.split('"')[1]
	print(field_name, ty_normal, correct_name)
	new_dtype = fpapi.getDataTypes(ty_normal)[0]
	try:
		ival = int(field_name.split("field_")[1])
	except:
		ival = int(field_name.split("field_")[1], 16)
	print(ival, new_dtype, new_dtype.getLength(), correct_name)
	dtype.replaceAtOffset(ival, new_dtype, new_dtype.getLength(), correct_name, "Autogenerated from XML")
