# TODO write a description for this script
# @author
# @category _Custom
# @keybinding
# @menupath
# @toolbar

import ghidra
from ghidra.app.decompiler.flatapi import FlatDecompilerAPI
from ghidra.app.script import GhidraState
from ghidra.app.util.cparser.C import CParser
from ghidra.program.flatapi import FlatProgramAPI
from ghidra.program.model.address import Address
from ghidra.program.model.data import (
	ArrayDataType,
	DataTypeConflictHandler,
	DataTypeManager,
	StringDataType,
	StructureDataType,
)
from ghidra.program.model.listing import Program


def get_state():
	# type: () -> GhidraState
	return getState()


def get_addr():
	# type: () -> Address
	return currentAddress


def hex_n(n):
	if n[0:2] == "0x":
		num = int(n, 16)
	else:
		num = int(n)
	return num


state = get_state()
addr = get_addr()
program = state.getCurrentProgram()
data_type_manager = program.getDataTypeManager()
fpapi = FlatProgramAPI(program)
fdapi = FlatDecompilerAPI(fpapi)
src = fdapi.decompile(program.getFunctionManager().getFunctionContaining(addr))

parts = src.split('",param')

struct = StructureDataType("ConfigExplosion", 0x174)
for k, v in enumerate(parts):
	if k == 0:
		continue
	name = parts[k - 1].split('"')[-1]
	ty = ""
	if len(parts[k - 1].split("Thingy_")) > 1:
		ty = parts[k - 1].split("Thingy_")[1].split("(")[0]
	real_ty = data_type_manager.getDataType("/" + ty)
	if real_ty is None:
		real_ty = data_type_manager.getDataType("noita.exe/" + ty)
	if real_ty is None:
		real_ty = data_type_manager.getDataType("/undefined1")
	offset = hex_n(v.split("+ ")[1].split(")")[0].split(",")[0])
	print(name, offset)
	struct.replaceAtOffset(
		offset, real_ty, real_ty.getLength(), name, "autogenerated by config struct"
	)
data_type_manager.addDataType(struct, DataTypeConflictHandler.DEFAULT_HANDLER)
